Add usage instructions to the readme
dancrumb/generator-serverless-policy pull request #36
Opened 2020-03-05 12:49 UTC by M1ke

I had to do various bits of Googling to be able to use this generator; thought I'd contribute by adding some basic instructions and avoiding pitfalls (e.g unsupported node version for the Yeoman version)

2020-03-05 12:52 UTC, dancrumb requested changes
Thanks for the updates. Couple of small tweaks and we're good to go

2020-03-05 12:52 UTC, dancrumb commented on README.md
> +_NB as of 2020-03-05 this requiest node >= v10_
Small typo here

2020-03-05 12:52 UTC, dancrumb commented on README.md
> +The generator will ask questions about region, stage, DynamoDB and S3 before outputting a policy. If this is the first time you have used Yeoman the tool will prompt you about sharing analytics with
Could you clarify that it is yeoman asking for analytics and not this generator, please?

2020-03-15 19:51 UTC, M1ke commented
Done those changes

2020-06-05 15:06 UTC, merged

2020-06-05 15:06 UTC, dancrumb commented
Thanks!